# Generated by Django 4.2.16 on 2026-10-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('assigned', 'Assigned'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('logged_in', 'Logged In'), ('logged_out', 'Logged Out'), ('changed', 'Changed'), ('uploaded', 'Uploaded'), ('downloaded', 'Downloaded'), ('shared', 'Shared'), ('deactivated', 'Deactivated'), ('activated', 'Activated')], max_length=30)),
                ('module', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning')], default='success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='TaskWave Solutions', max_length=200)),
                ('org_email', models.EmailField(blank=True, max_length=254)),
                ('org_phone', models.CharField(blank=True, max_length=20)),
                ('org_address', models.TextField(blank=True)),
                ('org_website', models.URLField(blank=True)),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to='org/')),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=500)),
                ('smtp_sender_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_sender_name', models.CharField(blank=True, max_length=200)),
                ('primary_color', models.CharField(default='#b45309', max_length=20)),
                ('sidebar_style', models.CharField(default='default', max_length=20)),
                ('font_size', models.CharField(default='medium', max_length=20)),
                ('date_format', models.CharField(default='DD MMM YYYY', max_length=50)),
                ('time_format', models.CharField(default='12', max_length=20)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('allow_company_network_only', models.BooleanField(default=False)),
                ('allow_overtime_requests', models.BooleanField(default=True)),
                ('require_overtime_approval', models.BooleanField(default=True)),
                ('track_overtime_separately', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
