# Generated by Django 4.2.16 on 2026-10-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('task_submitted', 'Task Submitted'), ('task_approved', 'Task Approved'), ('changes_requested', 'Changes Requested'), ('new_message', 'New Message'), ('mention', 'Mention'), ('project_update', 'Project Update'), ('overtime_request', 'Overtime Request'), ('overtime_decision', 'Overtime Decision'), ('meeting_invite', 'Meeting Invitation'), ('file_shared', 'File Shared'), ('deadline_approaching', 'Deadline Approaching'), ('member_joined', 'Member Joined'), ('system', 'System')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('task_updates', models.BooleanField(default=True)),
                ('project_updates', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('overtime_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
